# Generated by Django 2.1.5 on 2019-04-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='BookLife\\static\\css/')),
                ('name_book', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('author', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('publishing', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('book_series', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('language', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('year', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('translator', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('count', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('binding', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('paper', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('literature', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
